# Generated by Django 5.0.6 on 2024-07-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carte',
        ),
    ]
