# Generated by Django 5.0.6 on 2024-07-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carte',
            new_name='Schema',
        ),
    ]
